#!/bin/bash

read -d '' HELP <<"EOF"
    Commit all added, changed, and removed files.
    Push the commit to the remote repository.
EOF

source "${HOME}/Shell/App/Git/Scripts/base.bash"

git add --all --no-ignore-removal
DATE="$(date +'%Y-%m-%d %H:%M')"
if [ -z "$1" ]; then
    MESSAGE="WIP: $(date +'%Y-%m-%d %H:%M')"
else
    MESSAGE="${1}"
fi
git commit -m "${MESSAGE}"
git push --progress origin $(git symbolic-ref --short HEAD)
