#!/bin/bash

HELP="Used to relink the local branch with the remote upstream"
source "${HOME}/Shell/App/Git/Scripts/base.bash"

git branch --set-upstream-to=origin/$(git symbolic-ref --short HEAD) $(git symbolic-ref --short HEAD)
