#!/bin/bash

read -d '' HELP <<"EOF"
    Show a nicely formatted list fo all branches
    Push the commit to the remote repository.
EOF
source "${HOME}/Shell/App/Git/Scripts/base.bash"

git for-each-ref \
    --sort=-committerdate refs/heads/ \
    --sort=-committerdate \
    --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
