#!/bin/bash
# Unstage last commit and all its files

if [[ "${1}" != 'yes' ]]; then
    printf "\n"
    printf "      \e[91mATENTION \e[39m\n"
    printf "      \e[33mThis will drop your last commit and replace the files to the workspace.\e[39m\n"
    printf "      \e[33mIf you really want to doi, call git unstage with the ´yes´parameter: \e[39m\n"
    printf "      \e[96m\e[4mgit unstage yes \e[39m\n"
    printf "\n"

    exit 1
fi

git reset --soft HEAD~1
