#!/bin/bash
HELP="Checkout to a branch, if it exists."
source "${HOME}/Shell/App/Git/Scripts/base.bash"

if [[ -e "${1}" ]]; then
    git checkout "${1}"
    exit 0
fi

# Try to checkout to given branch name
git rev-parse --verify "${1}" >> /dev/null 2>&1
if [[ $? -eq 0 ]]; then
    git checkout "${1}"
    exit 0
fi

# Try to append "GUEST-" to the branch name and checkout
git rev-parse --verify "GUEST-${1}" >> /dev/null 2>&1
if [[ $? -eq 0 ]]; then
    git checkout "GUEST-${1}"
    exit 0
fi

# Try to checkout to the local branches
branches=$(git for-each-ref --format='%(refname:short)' refs/heads/*) >> /dev/null 2>&1
for branch in $branches; do
    if [[ "${branch}" == "GUEST-${1}" ]]; then
        git checkout "GUEST-${branch}"
        printf " \e[93mThe branch ${1} does not exist localy, but I checked out to "GUEST-${branch}".\e[39m\n"
        exit 0
    fi

    if [[ "${branch}" == *"${1}"* ]]; then
        git checkout "${branch}"
        printf " \e[93mThe branch ${1} does not exist localy, but I checked out to "${branch}".\e[39m\n"
        exit 0
    fi
done

# Try to checkout to the remote branches
git fetch
branches=$(git branch -a)
for branch in $branches; do
    if [[ "${branch}" == *"GUEST-${1}"* ]]; then
        THE_BRANCH=${branch#*remotes\/origin\/}
        git checkout "${THE_BRANCH}"
        printf " \e[93mThe branch ${1} does not exist localy, but I checked out to "${branch}".\e[39m\n"
        exit 0
    fi

    if [[ "${branch}" == *"${1}"* ]]; then
        THE_BRANCH=${branch#*remotes\/origin\/}
        git checkout "${THE_BRANCH}"
        printf " \e[93mThe branch ${1} does not exist localy, but I checked out to "${branch}".\e[39m\n"
        exit 0
    fi
done

printf " \e[91mThe branch ${1} does not exist.\e[39m\n"


remotes/origin/
