#!/bin/bash

source "${HOME}/Shell/App/Git/Scripts/base.bash"

git add --all --no-ignore-removal
DATE="$(date +'%Y-%m-%d %H:%M')"
if [ -z "$1" ]; then
    MESSAGE="WIP: $(date +'%Y-%m-%d %H:%M')"
else
    MESSAGE="${1}"
fi
git commit -m "${MESSAGE}"
git push --progress origin $(git symbolic-ref --short HEAD)
