#!/bin/bash

HELP="Completely replace the local with the remote branch"
source "${HOME}/Shell/App/Git/Scripts/base.bash"

read -p "Are sure you want to replace your local branch with its remote counterpart?" -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    git reset --hard origin/$(git symbolic-ref --short HEAD)
endif

