#!/bin/bash

HELP="Completely replace the local with the remote branch"
source "${HOME}/Shell/App/Git/Scripts/base.bash"

read -p "Are sure you want to replace your local branch with its remote counterpart?" -n 1 -r
printf "\n\n"

BRANCH=origin/$(git symbolic-ref --short HEAD)

if [[ $REPLY =~ ^[Yy]$ ]]; then
    git reset --hard $BRANCH
fi

