#!/bin/bash

HELP="Check out the primary branch on the upstream remote."
source "${HOME}/Shell/App/Git/Scripts/base.bash"

git fetch-upstream

UPSTREAM=`git upstream-branch`
# TODO stash if tree is dirty
git checkout $UPSTREAM
