#!/bin/bash
HELP="Show the difference compared to the upstream branch."
source "${HOME}/Shell/App/Git/Scripts/base.bash"

git fetch-upstream

UPSTREAM=`git upstream-branch`
git diff `git merge-base $UPSTREAM HEAD` "$@"
